# 機械学習関連キーワード（abstractでフィルタリング用）
ML_KEYWORDS = [
    "growing",
    "machine learning",
    "deep learning",
    "neural network",
    "artificial intelligence",
    "reinforcement learning",
    "supervised learning",
    "unsupervised learning",
    "convolutional",
    "transformer",
    "gradient descent",
    "feature learning",
    "pattern recognition",
    "data mining",
    "classification",
    "regression",
    "clustering",
    "dimensionality reduction",
    "ensemble learning",
    "support vector",
    "random forest",
    "decision tree",
    "k-means",
    "neural net",
    "CNN",
    "RNN",
    "LSTM",
    "GAN",
    "model",
    "autoencoder",
    "attention mechanism",
    "self-attention",
    "multi-head attention",
    "bert",
    "gpt",
    "diffusion model",
    "stable diffusion",
    "variational autoencoder",
    "VAE",
    "generative adversarial",
    "optimization",
    "adam optimizer",
    "backpropagation",
    "batch normalization",
    "dropout",
    "regularization",
    "overfitting",
    "cross-validation",
    "hyperparameter",
    "embedding",
    "word2vec",
    "fasttext",
    "nlp",
    "natural language processing",
    "computer vision",
    "image recognition",
    "object detection",
    "semantic segmentation",
    "yolo",
    "resnet",
    "vgg",
    "inception",
    "mobilenet",
    "efficientnet",
    "vision transformer",
    "vit",
    "contrastive learning",
    "self-supervised",
    "few-shot learning",
    "zero-shot learning",
    "meta-learning",
    "transfer learning",
    "fine-tuning",
    "pre-training",
    "foundation model",
    "large language model",
    "llm",
    "chatbot",
    "conversational ai",
    "recommendation system",
    "collaborative filtering",
    "content-based filtering",
    "time series",
    "forecasting",
    "anomaly detection",
    "outlier detection",
    "adversarial training",
    "CLIP",
    "adversarial attack",
    "robustness",
    "interpretability",
    "explainable ai",
    "xai",
    "federated learning",
    "edge computing",
    "model compression",
    "quantization",
    "pruning",
    "knowledge distillation",
    "multi-modal",
    "multimodal",
    "cross-modal",
    "speech recognition",
    "text-to-speech",
    "voice synthesis",
    "robotics",
    "autonomous",
    "reinforcement",
    "q-learning",
    "policy gradient",
    "actor-critic",
    "multi-agent",
    "gaussian process",
    "bayesian",
    "probabilistic",
    "monte carlo",
    "markov chain",
    "hidden markov",
    "expectation maximization",
    "principal component",
    "pca",
    "independent component",
    "manifold learning",
    "tsne",
    "umap",
    "graph neural network",
    "gnn",
    "graph convolution",
    "knowledge graph",
    "graph embedding",
    "network analysis",
    "social network",
    "causal inference",
    "causal discovery",
    "fairness",
    "ethical ai",
    "privacy",
    "differential privacy",
    "homomorphic encryption",
    "secure computation",
    "blockchain",
    "cryptocurrency",
    "decentralized",
    "distributed learning",
    "parallel computing",
    "gpu",
    "cuda",
    "tensor",
    "pytorch",
    "tensorflow",
    "keras",
    "scikit-learn",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "jupyter",
    "notebook",
    "mlops",
    "model deployment",
    "continuous integration",
    "a/b testing",
    "experiment design",
    "statistical significance",
    "hypothesis testing",
    "correlation",
    "feature selection",
    "feature engineering",
    "data preprocessing",
    "data augmentation",
    "synthetic data",
    "generative model",
    "discriminative model",
    "likelihood",
    "maximum likelihood",
    "loss function",
    "cost function",
    "objective function",
    "activation function",
    "relu",
    "sigmoid",
    "tanh",
    "softmax",
    "layer normalization",
    "weight initialization",
    "learning rate",
    "momentum",
    "early stopping",
    "model selection",
    "ensemble method",
    "bagging",
    "boosting",
    "gradient boosting",
    "xgboost",
    "lightgbm",
    "catboost",
    "stacking",
    "voting",
    "blending",
]

# 材料関連キーワード（CS系カテゴリ用）
MATERIAL_KEYWORDS = [
    "material",
    "materials",
    "crystal",
    "crystalline",
    "semiconductor",
    "superconductor",
    "polymer",
    "composite",
    "nanoparticle",
    "nanomaterial",
    "nanotechnology",
    "graphene",
    "carbon nanotube",
    "quantum dot",
    "thin film",
    "surface",
    "interface",
    "catalyst",
    "photovoltaic",
    "solar cell",
    "battery",
    "electrode",
    "electrolyte",
    "ionic",
    "electronic",
    "optical",
    "magnetic",
    "ferroelectric",
    "piezoelectric",
    "thermoelectric",
    "mechanical properties",
    "elastic",
    "plastic",
    "fracture",
    "fatigue",
    "corrosion",
    "oxidation",
    "reduction",
    "synthesis",
    "characterization",
    "microscopy",
    "spectroscopy",
    "diffraction",
    "scattering",
    "phase transition",
    "phase diagram",
    "alloy",
    "intermetallic",
    "ceramic",
    "glass",
    "biomaterial",
    "biocompatible",
    "drug delivery",
    "tissue engineering",
    "scaffold",
    "hydrogel",
    "membrane",
    "coating",
    "additive manufacturing",
    "3D printing",
    "powder metallurgy",
    "sintering",
    "annealing",
    "doping",
    "defect",
    "vacancy",
    "dislocation",
    "grain boundary",
    "microstructure",
    "nanostructure",
    "atomic structure",
    "molecular dynamics",
    "density functional theory",
    "DFT",
    "ab initio",
    "first principles",
    "band structure",
    "electronic structure",
    "phonon",
    "lattice",
    "crystallography",
    "solid state",
    "condensed matter",
    "materials science",
    "materials engineering",
    "metallurgy",
    "tribology",
    "wear",
    "friction",
    "lubrication",
    "hardness",
    "strength",
    "toughness",
    "ductility",
    "brittleness",
    "conductivity",
    "resistivity",
    "dielectric",
    "permittivity",
    "permeability",
    "refractive index",
    "absorption",
    "emission",
    "luminescence",
    "fluorescence",
    "phosphorescence",
    "energy storage",
    "energy conversion",
    "fuel cell",
    "hydrogen storage",
    "lithium ion",
    "sodium ion",
    "solid electrolyte",
    "perovskite",
    "MOF",
    "metal-organic framework",
    "zeolite",
    "porous material",
    "surface area",
    "adsorption",
    "desorption",
    "catalysis",
    "photocatalysis",
    "electrocatalysis",
    "heterogeneous catalysis",
    "homogeneous catalysis",
]
