# 機械学習関連キーワード（abstractでフィルタリング用）
ML_KEYWORDS = [
    "machine learning",
    "deep learning",
    "neural network",
    "artificial intelligence",
    "reinforcement learning",
    "supervised learning",
    "unsupervised learning",
    "convolutional",
    "transformer",
    "gradient descent",
    "feature learning",
    "pattern recognition",
    "data mining",
    "classification",
    "regression",
    "clustering",
    "dimensionality reduction",
    "ensemble learning",
    "support vector",
    "random forest",
    "decision tree",
    "k-means",
    "neural net",
    "CNN",
    "RNN",
    "LSTM",
    "GAN",
    "model",
    "autoencoder",
    "attention mechanism",
    "self-attention",
    "multi-head attention",
    "bert",
    "gpt",
    "diffusion model",
    "stable diffusion",
    "variational autoencoder",
    "VAE",
    "generative adversarial",
    "optimization",
    "adam optimizer",
    "backpropagation",
    "batch normalization",
    "dropout",
    "regularization",
    "overfitting",
    "cross-validation",
    "hyperparameter",
    "embedding",
    "word2vec",
    "fasttext",
    "nlp",
    "natural language processing",
    "computer vision",
    "image recognition",
    "object detection",
    "semantic segmentation",
    "yolo",
    "resnet",
    "vgg",
    "inception",
    "mobilenet",
    "efficientnet",
    "vision transformer",
    "vit",
    "contrastive learning",
    "self-supervised",
    "few-shot learning",
    "zero-shot learning",
    "meta-learning",
    "transfer learning",
    "fine-tuning",
    "pre-training",
    "foundation model",
    "large language model",
    "llm",
    "chatbot",
    "conversational ai",
    "recommendation system",
    "collaborative filtering",
    "content-based filtering",
    "time series",
    "forecasting",
    "anomaly detection",
    "outlier detection",
    "adversarial training",
    "CLIP",
    "adversarial attack",
    "robustness",
    "interpretability",
    "explainable ai",
    "xai",
    "federated learning",
    "edge computing",
    "model compression",
    "quantization",
    "pruning",
    "knowledge distillation",
    "multi-modal",
    "multimodal",
    "cross-modal",
    "speech recognition",
    "text-to-speech",
    "voice synthesis",
    "robotics",
    "autonomous",
    "reinforcement",
    "q-learning",
    "policy gradient",
    "actor-critic",
    "multi-agent",
    "gaussian process",
    "bayesian",
    "probabilistic",
    "monte carlo",
    "markov chain",
    "hidden markov",
    "expectation maximization",
    "principal component",
    "pca",
    "independent component",
    "manifold learning",
    "tsne",
    "umap",
    "graph neural network",
    "gnn",
    "graph convolution",
    "knowledge graph",
    "graph embedding",
    "network analysis",
    "social network",
    "causal inference",
    "causal discovery",
    "fairness",
    "ethical ai",
    "privacy",
    "differential privacy",
    "homomorphic encryption",
    "secure computation",
    "blockchain",
    "cryptocurrency",
    "decentralized",
    "distributed learning",
    "parallel computing",
    "gpu",
    "cuda",
    "tensor",
    "pytorch",
    "tensorflow",
    "keras",
    "scikit-learn",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "jupyter",
    "notebook",
    "mlops",
    "model deployment",
    "continuous integration",
    "a/b testing",
    "experiment design",
    "statistical significance",
    "hypothesis testing",
    "correlation",
    "feature selection",
    "feature engineering",
    "data preprocessing",
    "data augmentation",
    "synthetic data",
    "generative model",
    "discriminative model",
    "likelihood",
    "maximum likelihood",
    "loss function",
    "cost function",
    "objective function",
    "activation function",
    "relu",
    "sigmoid",
    "tanh",
    "softmax",
    "layer normalization",
    "weight initialization",
    "learning rate",
    "momentum",
    "early stopping",
    "model selection",
    "ensemble method",
    "bagging",
    "boosting",
    "gradient boosting",
    "xgboost",
    "lightgbm",
    "catboost",
    "stacking",
    "voting",
    "blending"
]
